### PR TITLE
Add default image when missing contents

### PR DESCRIPTION
**Pull request by Erid**
And fix bug when validation the question value

## Screenshots
image

### CODE REVIEW

**Review by zleman1593 — APPROVED** [review]
Can we considering adding something like the text "photo already submitted? @robcurtis  What text would you use?

**Comment by Erid** [comment]
@zleman1593 Yes, it's a simple change. I did it this way for now, but once we have a better one I can update it in a few minutes.

**Comment by robcurtis** [comment]
@Erid @zleman1593 I don’t mind the blurred image. Except I have questions about the behavior of the camera/fileUpload component in that state when it's revisited after already being uploaded.

Can the old image (blurred) get removed and a new one added? Or is it set in stone after you’ve already submitted? That would inform what text we add there. Also how is it handled for camera questions where multiple photos are allowed? Will we show multiple blurred photos with the # equivalent to the # uploaded originally?

**Comment by Erid** [comment]
@robcurtis The blurred image can be removed (it's the equivalent of removing the original photo) and if they have multiple photos, they'll get multiple blurred photos, in the state the fileIds and everything are kept, we're just not showing them the actual photo.

**Comment by robcurtis** [comment]
@Erid thats great. We could add subtext like "You previously uploaded a photo for this question, and it's temporarily hidden to protect your privacy."

I think eventually, the ideal behavior would be to show the blurred image with an unlock watermark, which when pressed, reveals the image.

**Comment by robcurtis** [comment]
We decided we're going to exclude the subtext for now, and just include the blurred image. @Erid

**Pull request merged**
